### ISSUE TITLE
New categories in sandbox

### ISSUE THREAD

**Issue by g-mips** [byuicampuscd/gamification-with-units#1]
In order to fully test the product, I need some new categories, rightly named Unit1Required, Unit1Optional, Unit2Required, Unit2Optional, etc... I would need some grade items as well in these categories. Let me know the structure of the sandbox can be changed, or if you can make these, that would be great!

**Comment by meeple142** [comment]
Sure! in my sand box go right a head! If you need help doing it let me know

**Comment by g-mips** [comment]
Thanks for doing that for me! :)
